//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 10:55:37 PM EAT 
//


package org.akomantoso.schema.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;type xmlns="http://www.akomantoso.org/2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Complex&lt;/type&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;name xmlns="http://www.akomantoso.org/2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Amendments&lt;/name&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;comment xmlns="http://www.akomantoso.org/2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;The complex type Amendments is a list of all the amendment elements that can be used on a document analysis&lt;/comment&gt;
 * </pre>
 * 
 * 
 * <p>Java class for Amendments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Amendments">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.akomantoso.org/2.0}textualMod"/>
 *         &lt;element ref="{http://www.akomantoso.org/2.0}meaningMod"/>
 *         &lt;element ref="{http://www.akomantoso.org/2.0}scopeMod"/>
 *         &lt;element ref="{http://www.akomantoso.org/2.0}forceMod"/>
 *         &lt;element ref="{http://www.akomantoso.org/2.0}efficacyMod"/>
 *         &lt;element ref="{http://www.akomantoso.org/2.0}legalSystemMod"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Amendments", propOrder = {
    "textualModOrMeaningModOrScopeMod"
})
public class Amendments {

    @XmlElements({
        @XmlElement(name = "textualMod", type = TextualMod.class),
        @XmlElement(name = "meaningMod", type = MeaningMod.class),
        @XmlElement(name = "scopeMod", type = ScopeMod.class),
        @XmlElement(name = "forceMod", type = ForceMod.class),
        @XmlElement(name = "efficacyMod", type = EfficacyMod.class),
        @XmlElement(name = "legalSystemMod", type = LegalSystemMod.class)
    })
    protected List<ModificationType> textualModOrMeaningModOrScopeMod;

    /**
     * Gets the value of the textualModOrMeaningModOrScopeMod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textualModOrMeaningModOrScopeMod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextualModOrMeaningModOrScopeMod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextualMod }
     * {@link MeaningMod }
     * {@link ScopeMod }
     * {@link ForceMod }
     * {@link EfficacyMod }
     * {@link LegalSystemMod }
     * 
     * 
     */
    public List<ModificationType> getTextualModOrMeaningModOrScopeMod() {
        if (textualModOrMeaningModOrScopeMod == null) {
            textualModOrMeaningModOrScopeMod = new ArrayList<ModificationType>();
        }
        return this.textualModOrMeaningModOrScopeMod;
    }

}
