//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.11 at 11:34:41 PM EAT 
//


package org.oasis_open.docs.legaldocml.ns.akn._3_0.csd06;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;type xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Complex&lt;/type&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;name xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;subFlowStructure&lt;/name&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;comment xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 * the type subFlowStructure specifies the overall content model of the elements that are subFlows&lt;/comment&gt;
 * </pre>
 * 
 * 
 * <p>Java class for subFlowStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subFlowStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;group ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}documentType"/>
 *         &lt;group ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}blockElements"/>
 *         &lt;group ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}containerElements"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}tr"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}th"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}td"/>
 *         &lt;group ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}hierElements"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}content"/>
 *         &lt;group ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}ANcontainers"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}formula"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}recitals"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}citations"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}longTitle"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}recital"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}citation"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}componentRef"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}documentRef"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}intro"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}wrap"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}heading"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}subheading"/>
 *         &lt;element ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}num"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06}corereq"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subFlowStructure", propOrder = {
    "amendmentListOrOfficialGazetteOrDocumentCollection"
})
@XmlSeeAlso({
    QuotedStructure.class,
    AuthorialNote.class,
    ExtractStructure.class
})
public class SubFlowStructure {

    @XmlElementRefs({
        @XmlElementRef(name = "rollCall", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "question", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subchapter", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "statement", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "part", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "answer", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "longTitle", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "noticesOfMotion", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "proceduralMotions", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tr", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = Tr.class, required = false),
        @XmlElementRef(name = "subsection", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "act", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "title", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "toc", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = Toc.class, required = false),
        @XmlElementRef(name = "debateSection", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = DebateSection.class, required = false),
        @XmlElementRef(name = "citations", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "citation", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "p", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "table", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = Table.class, required = false),
        @XmlElementRef(name = "ol", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "officialGazette", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scene", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "questions", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "point", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bill", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "address", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "intro", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "blockList", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = BlockList.class, required = false),
        @XmlElementRef(name = "debateReport", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "td", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = Td.class, required = false),
        @XmlElementRef(name = "heading", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subpart", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ministerialStatements", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pointOfOrder", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fragment", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subdivision", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "narrative", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sublist", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "list", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "div", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "th", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = Th.class, required = false),
        @XmlElementRef(name = "ul", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "speech", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rule", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "formula", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = Formula.class, required = false),
        @XmlElementRef(name = "amendment", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "communication", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "componentRef", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "writtenStatements", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "book", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "proviso", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "blockContainer", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subclause", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recital", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "documentRef", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tome", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "papers", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subparagraph", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "foreign", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "documentCollection", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "oralStatements", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recitals", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subrule", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "adjournment", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "container", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "other", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "petitions", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "chapter", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "resolutions", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "block", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = Block.class, required = false),
        @XmlElementRef(name = "wrap", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "summary", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "division", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "judgment", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "prayers", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subtitle", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "section", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tblock", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nationalInterest", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "clause", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "declarationOfVote", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "amendmentList", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "administrationOfOath", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "personalStatements", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "doc", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "alinea", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "article", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "num", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subheading", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "transitional", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "paragraph", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "debate", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "indent", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "content", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "hcontainer", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = Hcontainer.class, required = false),
        @XmlElementRef(name = "speechGroup", namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD06", type = SpeechGroup.class, required = false)
    })
    protected List<Object> amendmentListOrOfficialGazetteOrDocumentCollection;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute(name = "style")
    protected String style;
    @XmlAttribute(name = "title")
    protected String titleAttr;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String space;
    @XmlAttribute(name = "refersTo")
    protected List<String> refersTo;
    @XmlAttribute(name = "currentId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String currentId;
    @XmlAttribute(name = "originalId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String originalId;
    @XmlAttribute(name = "GUID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String guid;
    @XmlAttribute(name = "alternativeTo")
    @XmlSchemaType(name = "anyURI")
    protected String alternativeTo;
    @XmlAttribute(name = "status")
    protected StatusType status;
    @XmlAttribute(name = "period")
    @XmlSchemaType(name = "anyURI")
    protected String period;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the amendmentListOrOfficialGazetteOrDocumentCollection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the amendmentListOrOfficialGazetteOrDocumentCollection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAmendmentListOrOfficialGazetteOrDocumentCollection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link SpeechType }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link OpenStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link SpeechType }{@code >}
     * {@link Tr }
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Blocksreq }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link HierarchicalStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link Toc }
     * {@link DebateSection }
     * {@link JAXBElement }{@code <}{@link CitationHierarchy }{@code >}
     * {@link Table }
     * {@link JAXBElement }{@code <}{@link ComplexTypeInline }{@code >}
     * {@link JAXBElement }{@code <}{@link ItemType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListItems }{@code >}
     * {@link JAXBElement }{@code <}{@link CollectionStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link ComplexTypeInline }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link HierarchicalStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link BlockList }
     * {@link JAXBElement }{@code <}{@link Blocksreq }{@code >}
     * {@link Td }
     * {@link JAXBElement }{@code <}{@link OpenStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Inlinereq }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link FragmentStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link ComplexTypeInline }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Blocksreq }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link Th }
     * {@link JAXBElement }{@code <}{@link ListItems }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link SpeechType }{@code >}
     * {@link Formula }
     * {@link JAXBElement }{@code <}{@link AmendmentStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link SrcType }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link BlockContainerType }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link ItemType }{@code >}
     * {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link AnyOtherType }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link CollectionStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link RecitalHierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link ContainerType }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Blocksreq }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link Block }
     * {@link JAXBElement }{@code <}{@link ComplexTypeInline }{@code >}
     * {@link JAXBElement }{@code <}{@link Blocksreq }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link JudgmentStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link ItemType }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link CollectionStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Althierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link OpenStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link DebateStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link ComplexTypeInline }{@code >}
     * {@link JAXBElement }{@code <}{@link ComplexTypeInline }{@code >}
     * {@link JAXBElement }{@code <}{@link Hierarchy }{@code >}
     * {@link JAXBElement }{@code <}{@link Blocksreq }{@code >}
     * {@link Hcontainer }
     * {@link SpeechGroup }
     * 
     * 
     */
    public List<Object> getAmendmentListOrOfficialGazetteOrDocumentCollection() {
        if (amendmentListOrOfficialGazetteOrDocumentCollection == null) {
            amendmentListOrOfficialGazetteOrDocumentCollection = new ArrayList<Object>();
        }
        return this.amendmentListOrOfficialGazetteOrDocumentCollection;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the titleAttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleAttr() {
        return titleAttr;
    }

    /**
     * Sets the value of the titleAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleAttr(String value) {
        this.titleAttr = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the refersTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refersTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefersTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRefersTo() {
        if (refersTo == null) {
            refersTo = new ArrayList<String>();
        }
        return this.refersTo;
    }

    /**
     * Gets the value of the currentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentId() {
        return currentId;
    }

    /**
     * Sets the value of the currentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentId(String value) {
        this.currentId = value;
    }

    /**
     * Gets the value of the originalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalId() {
        return originalId;
    }

    /**
     * Sets the value of the originalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalId(String value) {
        this.originalId = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGUID() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGUID(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the alternativeTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternativeTo() {
        return alternativeTo;
    }

    /**
     * Sets the value of the alternativeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternativeTo(String value) {
        this.alternativeTo = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriod(String value) {
        this.period = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
