//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.16 at 11:59:01 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0/CSD10", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.akomantoso.schema.v3.csd10;
